// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNI_Training_System;

#nullable disable

namespace UNI_Training_System.Migrations
{
    [DbContext(typeof(UNITrainingDbContext))]
    partial class UNITrainingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UNI_Training_System.Models.Communications_cs", b =>
                {
                    b.Property<int>("Communication_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Communication_ID"));

                    b.Property<string>("Meassage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sender_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Communication_ID");

                    b.ToTable("communications");
                });

            modelBuilder.Entity("UNI_Training_System.Models.Company", b =>
                {
                    b.Property<int>("Company_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_ID"));

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Last_updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Training_Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Company_ID");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("UNI_Training_System.Models.Student", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_ID"));

                    b.Property<int>("Password_Student")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Student_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Student_ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UNI_Training_System.Models.Training_programs", b =>
                {
                    b.Property<int>("Program_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Program_ID"));

                    b.Property<int>("Company_ID")
                        .HasColumnType("int");

                    b.Property<string>("Program_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Training_Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Program_ID");

                    b.ToTable("training_Programs");
                });

            modelBuilder.Entity("UNI_Training_System.Models.University", b =>
                {
                    b.Property<int>("University_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("University_ID"));

                    b.Property<int>("Company_ID")
                        .HasColumnType("int");

                    b.Property<int>("Company_Name")
                        .HasColumnType("int");

                    b.Property<int>("Password_Student")
                        .HasColumnType("int");

                    b.Property<string>("Student_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Training_Field")
                        .HasColumnType("int");

                    b.Property<string>("University_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("University_ID");

                    b.ToTable("Universities");
                });
#pragma warning restore 612, 618
        }
    }
}
